- name: update/upgrade
  become: true
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: install ufw & nginx
  become: true 
  ansible.builtin.apt:
    name:
      - ufw
      - nginx
      - fail2ban
    state: present

- name: allow port 22 for ssh
  become: true
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: enable ufw
  become: true
  community.general.ufw:
    state: enabled

- name: create admin user, add to sudo
  become: true
  ansible.builtin.user:
    name: admin
    password: "{{'1234' | password_hash('sha512') }}"
    update_password: on_create
    groups: sudo
    append: true

- name: add SSH key for admin user
  authorized_key:
    user: admin
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: lock root
  become: true
  ansible.builtin.user:
    name: root
    password_lock: yes

- name: enable fail2ban
  become: true
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started

- name: allow port 80 for http
  become: true
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: create normal user #no sudo
  user:
    name: "{{ item }}"
    state: present
  loop: 
    - user1
    - user2
    - user3
    - user4

- name: create nginx site config
  become: true
  ansible.builtin.copy:
    src: roles/users/files/miniprojekti.conf
    dest: /etc/nginx/sites-available/miniprojekti.conf
  notify: restart nginx

- name: disable nginx default site
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: copy website files
  become: true
  ansible.builtin.copy:
    src: roles/users/files/
    dest: /var/www/projektisivu/
  notify: restart nginx
     
- name: enable site
  become: true
  file:
    src: /etc/nginx/sites-available/miniprojekti.conf
    dest: /etc/nginx/sites-enabled/miniprojekti.conf
    state: link

- name: other usefull packages
  become: true
  ansible.builtin.apt:
    name:
      - micro
      - bash-completion
      - openssh-client
      - wget
      - curl
      - tree
    state: present

